service: service-random-generator
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs16.x
  lambdaHashingVersion: 20201221
  timeout: 10
  memorySize: 128
  logRetentionInDays: 7
  tracing:
    lambda: true
    apiGateway: true
            
resources:
  Resources:

package:
  individually: true

functions:
  get-random-number:
    handler: src/handlers/random-number/index.handler
    events:
      - http:
          path: random/number
          method: get
          private: true

plugins:
  - serverless-esbuild
  - serverless-prune-plugin # for removing old lambda versions
  - serverless-offline
  
custom:	
  esbuild:
    minify: false
    bundle: true
    sourcemap: true
    watch:
      pattern:
        ['src/**/*.ts']
      ignore: ['.serverless/**/*', '.build', '.esbuild']

  prune:
    automatic: true
    number: 5

