name: core-master

on:
  push:
    branches: ['main']
    paths:
      - core/**

jobs:
  build:
    name: Build core master
    uses: flaviostutz/gh-makefile/.github/workflows/make-ci.yml@main
    with:
      working-directory: ./core
      tooling: node
      tooling-version: 16
      tooling-cache: yarn
      target-build: true
      target-lint: true
      target-unit-tests: true
