name: tag-publish

on:
  push:
    tags:
      - '*'

jobs:
  build-affected:
    name: Core build, lint and test
    uses: flaviostutz/gh-makefile/.github/workflows/make-ci.yml@main
    with:
      working-directory: ./
      tooling: node
      tooling-version: 16
      tooling-cache: yarn
      stage: prd
      target-build: true
      target-lint: true
      target-unit-tests: true

  publish-affected:
    runs-on: ubuntu-latest
    needs: [ build-core, build-middy ]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          cache: yarn
      - run: make build
        working-directory: ./
      - run: make publish
        working-directory: ./
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_ACCESS_TOKEN }}
